[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-interaction-protocol"
version = "0.1.0"
description = "Agent Interaction Protocol"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "build",
    "twine"
]
http = [
    "fastapi",
    "uvicorn",
    "httpx"
]
